version: '3.8'
services:
  mysql_db:
    image: mysql:8.0.32
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: viva#1919
      MYSQL_DATABASE: demodb2 
    ports:
      - "3307:3306"
    volumes:
      - load_test_db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '0.5'  # Limit CPU usage to 0.5 cores
          memory: 512M  # Limit memory usage to 512 MB

  redis:
    image: redis:7.0.10
    container_name: redis
    restart: always
    env_file:
      - .env
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.5'  # Limit CPU usage to 0.5 cores
          memory: 256M  # Limit memory usage to 256 MB

  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "9011:9011"
    env_file:
      - .env
    depends_on:
      - mysql_db
      - redis
    links:
      - mysql_db
      - redis
    deploy:
      resources:
        limits:
          cpus: '1'  # Limit CPU usage to 1 core
          memory: 1G  # Limit memory usage to 1 GB
    volumes:   
      - app_data:/app/data

  load_test_server:
    build:
      context: ./load_test
      dockerfile: ./Dockerfile
    ports:
      - "9012:9012"
    deploy:
      resources:
        limits:
          cpus: '3'  # Limit CPU usage to 1 core
          memory: 2G  # Limit memory usage to 1 GB
    volumes:  
      - load_test_tool_data:/load_test/data

volumes:    
  load_test_tool_data:
  app_data:
  load_test_db_data:
