version: '3.8'
services:
  load_test:
    build:
      context: .
      dockerfile: ./load_test/Dockerfile
    ports:
      - "9012:9012"
    deploy:
      resources:
        limits:
          cpus: '3'  # Limit CPU usage to 1 core
          memory: 2G  # Limit memory usage to 1 GB


volumes:
  load_test_tool_data:
